@SERVER=https://sandbox.zipup.dev
### get inmates
GET {{SERVER}}/inmates


### get guards
GET {{SERVER}}/guards?rank=Captain


### Add inmate
PATCH  {{SERVER}}/inmates/3

{
  "cell": "A-23"
}

### Get tasks
GET {{SERVER}}/tasks