# @server=http://localhost:3000
@server=http://postgres.localhost:3000
### create new post

POST {{server}}/posts

{
  "title": "My First Post",
  "content": "This is the content of my first post.",
  "status" : "PUBLISHED"
}

### get all posts
GET {{server}}/posts

