services:
  
  postgres:
    image: postgres:17-bookworm
    container_name: zipup-example
    restart: unless-stopped
    logging:
      driver: none
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: zipup
      POSTGRES_PASSWORD: zipup
volumes:
  postgres_data: